version: build_{build}
build:
  verbosity: minimal

image: Visual Studio 2015

install:
- mkdir ..\thirdparty
- cd ..\thirdparty
- appveyor DownloadFile http://rdb.name/thirdparty-vc14-x64.7z
- 7z x thirdparty-vc14-x64.7z

- C:\mingw\msys\1.0\bin\patch.exe -p1 < %APPVEYOR_BUILD_FOLDER%\temp\0001-Patch-CMake-config-files.patch
- cd %APPVEYOR_BUILD_FOLDER%

build_script:
- mkdir build
- cd build
- ps: >
        $libs_prefix=(Get-ChildItem -Attributes Directory ..\..\thirdparty\win-libs-vc14-x64).fullname -join ";"

        cmake -G"Visual Studio 14 2015 Win64"
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_PREFIX_PATH="$libs_prefix"
        -DJPEG_LIBRARY=..\..\thirdparty\win-libs-vc14-x64\jpeg\lib\jpeg-static.lib
        -DPNG_LIBRARY=..\..\thirdparty\win-libs-vc14-x64\png\lib\libpng16_static.lib
        -DZLIB_LIBRARY=..\..\thirdparty\win-libs-vc14-x64\zlib\lib\zlibstatic.lib
        .. 2>&1 | %{ "$_" }
- msbuild /p:Configuration=Release ALL_BUILD.vcxproj
