version: build_{build}
build:
  verbosity: minimal

image: Visual Studio 2015

environment:
  matrix:
  # Python 3.6 (both compilers)
  - MSBUILD_TOOLSET: llvm
    PYTHON_VERSION: 36-x64
    EXTRA_FLAGS: "-DBT_NO_SIMD_OPERATOR_OVERLOADS"
  - MSBUILD_TOOLSET: v140
    PYTHON_VERSION: 36-x64

  # Python 2.7 (both compilers)
  - MSBUILD_TOOLSET: llvm
    PYTHON_VERSION: 27-x64
    EXTRA_FLAGS: "-DBT_NO_SIMD_OPERATOR_OVERLOADS"
  - MSBUILD_TOOLSET: v140
    PYTHON_VERSION: 27-x64

install:
- mkdir ..\thirdparty
- cd ..\thirdparty

- appveyor DownloadFile http://rdb.name/thirdparty-vc14-x64.7z
- 7z x thirdparty-vc14-x64.7z

- cd %APPVEYOR_BUILD_FOLDER%

build_script:
- mkdir build
- cd build
- ps: $env:libs_prefix=(Get-ChildItem -Attributes Directory ..\..\thirdparty\win-libs-vc14-x64).fullname -join ";"
- ps: $env:thirdparty_path=(Resolve-Path ..\..\thirdparty)

- cmd: >
        cmake -G"Visual Studio 14 2015 Win64" -T %MSBUILD_TOOLSET%
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_C_FLAGS="%EXTRA_FLAGS%"
        -DCMAKE_CXX_FLAGS="%EXTRA_FLAGS%"
        -DCMAKE_PREFIX_PATH="%libs_prefix%;C:\Python%PYTHON_VERSION%"
        -DJPEG_LIBRARY=%thirdparty_path%\win-libs-vc14-x64\jpeg\lib\jpeg-static.lib
        -DPNG_LIBRARY=%thirdparty_path%\win-libs-vc14-x64\png\lib\libpng16_static.lib
        -DZLIB_LIBRARY=%thirdparty_path%\win-libs-vc14-x64\zlib\lib\zlibstatic.lib
        ..
- msbuild /p:Configuration=Release /m ALL_BUILD.vcxproj

before_test:
- ps: $env:PATH=$env:PATH+";"+((Get-ChildItem ..\..\thirdparty\win-libs-vc14-x64\*\bin).fullname -join ";")
- cmd: C:\Python%PYTHON_VERSION%\python -m pip install pytest

test_script:
- ctest -VV
