language: cpp
sudo: false

# Build matrix:
os:
- windows
compiler:
- clang
- cl
env:
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=OFF COMPOSITE_SOURCE_LIMIT=30
- BUILD_METALIBS=ON COMPOSITE_SOURCE_LIMIT=0

before_install:
# clean up remnants of makepanda
- mv makepanda/test_imports.py .
- makepanda/selfdestruct.py --yes
# take care of installing Python
- cinst -y python
# create venv
- /c/Python37/python -m venv venv
- source venv/Scripts/activate

install:
- pip install pytest

before_script:
- mkdir built
- cd built

script:
- >
    cmake -G'Visual Studio 15 2017' -DBUILD_METALIBS=$BUILD_METALIBS \
    -DCOMPOSITE_SOURCE_EXCLUSIONS="$COMPOSITE_SOURCE_EXCLUSIONS" \
    -DCOMPOSITE_SOURCE_LIMIT=$COMPOSITE_SOURCE_LIMIT ..
- cmake --build . --config Debug -- /m

- export PYTHONPATH=$PWD
- python ../test_imports.py
- pytest -v ../tests
